### PR TITLE
V1

### PR DESCRIPTION
**Pull request by OsirisTerje**
Updated to use NUnit 3.0.1
Version number set to 1.0.0

### CODE REVIEW

**Comment by CharliePoole** [comment]
I see you are setting version to 1.0.0. Are you ready to do a formal release? If so, I'd like us to give it a more thorough review than we have been doing for this project, since it's about to become an official NUnit product.

OTOH, if you are still working on it, you should keep the version below 1.0 for now.

**Comment by rprouse** [comment]
Looks good to me. I've also given the previous version a decent test run. I don't use it much, but it worked well and I didn't have any problems with it.

**Comment by OsirisTerje** [comment]
I have done what I intended, the most important things were 1) Give it some time to run and Catch potential bugs,  2)  wait for the official NUnit3 release.  I think both are in now.  
It should have some unit tests, currently there are none, and I feel bad about that.  The code is very dependent upon what it extends, so it is not that easy, and I would like some more information on the code from MS.  We could either let it be a 0.95 until that is resolved, or let it go as a 1.0 now, and update with unit tests later.

**Comment by CharliePoole** [comment]
So is that a yes to my question about doing a formal release? :-)

FYI, going from a 0.x release to a 1.0 is a real big deal in my book although I realize it is not in many other open source projects. To me 0.x says "you take your chances" while 1.0 says "we believe this is ready for production use."

I have some other stuff to finish up and then I'll give it a try.

**Comment by OsirisTerje** [comment]
That is a yes, yes :-)

**Comment by CharliePoole** [comment]
@OsirisTerje I'm reviewing all the code, since I have never reviewed your earlier commits. @rprouse if you are in the same situation, it would be great if you too looked at the entire (not very big) codebase.

**Comment by CharliePoole** [comment]
Regrettably, I can only test part of this, since I only have VS2015 community edition.

**Comment by CharliePoole** [comment]
Can we get a LICENSE into the root? We should also have a change list and notice file if appropriate.

In a separate note, I asked about what Microsoft's rights to this code are and what we have from them that permits us to use it.

**Comment by CharliePoole** [comment]
Many source files have no standard header. Some source files have a header that says the code belongs to Microsoft.

**Comment by rprouse** [comment]
I can only test the test creation stuff also. I believe that the intellitest stuff requires VS Ultimate. I only have professional.

I will take a look at the entire codebase as you asked.

**Comment by CharliePoole** [comment]
I'm in the same boat, with only the community edition.

**Comment by OsirisTerje** [comment]
Does this look ok now to merge ?  Should we release as 1.0 or do a 0.9 ?

**Comment by rprouse** [comment]
I think we are okay to merge and probably for a 1.0 release. This has been out there for awhile now and nobody has reported any issues. Do you agree?

**Comment by CharliePoole** [comment]
I'm still conflicted about supporting this, for reasons we already discussed, but I know both of you are interested in having it. Since we are doing it I guess we should do a 1.0 release if you think it's ready. 

But let's keep in mind that for NUnit, unlike some other projects, a production release has always meant something quite different from an alpha, beta or pre-release. Even the 3.0 adapter, which has had a lot of work, is still not production-ready by our usual standards. I keep telling people not to use it for production work!!!

So, I guess what I am saying is that if you call it 1.0, you are saying that this is ready for use in a production context.

**Comment by OsirisTerje** [comment]
Ok, do I read you right that your advice is to release a 0.9 beta now ?     I am not opposed to that, the most important thing here is to get it to use the latest nunit release.

**Comment by CharliePoole** [comment]
@OsirisTerje I have not used the package. In fact, I can't use all it's features because it depends on a very expensive version of Visual Studio that I don't plan to buy.

So I can only give you the criterion I think you should use to make the decision yourself. That is, if you call it 1.0, you are saying that it's ready for use in production development situations. If, in your opiniion, it's not ready, then you should call it 0.9 or something. Conventionally, pre-1.0 releases are not yet ready for prime time. Did you have some goals for a 1.0 release? Has the package met those?

Of course, you are right to look for input but in this case I can't give you any more than that.

**Comment by OsirisTerje** [comment]
I can't see anything more the extension in itself should do, so yes, the goals are met.  I'll publish a 1.0 version during the weekend.

**Comment by CharliePoole** [comment]
Sounds good to me. :-)

**Pull request merged**
