### PR TITLE
Updated vsix to vsix3 for Visual Studio 2017  #8

### PR DESCRIPTION
**Pull request by OsirisTerje**
The VSIX is updated to format vsix3, ref #8  

Testing is done for VS 15 (vnext), but needs to be done for VS 2015 too before merging.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Do we have a statement in the readme or elsewhere about what verisons of VS are supported? If so, we should test on all those versions or announce a breaking change if some no longer work.

The updating of the version right in the master branch is not how we do our major packages, but since this is a simple single-assembly extension, it seems reasonable to do it this way.

**Comment by rprouse** [comment]
I would like to hold off on releasing this until we can confirm that the binding redirects have been fixed. To be safe, should we also hold off merging until then?

**Comment by CharliePoole** [comment]
@rprouse Since I don't know what the binding redirects are actually about, I defer to your judgement. 😄

**Comment by OsirisTerje** [comment]
@rprouse Yes, I think so.   But .... see below
@CharliePoole We found there are 4 missing binding redirects, to MIcrosoft assemblies,  in the Visual Studio devenv.exe.config.  The MS people have been informed and confirmed they will get these in.  We build to the earliest version, VS 2015 in this case, and the redirects are needed to make it work in VS 15 (vNext).  
So, it is not really up to us.  We could release, and then it is up to MS if it will work in VS 15 or not.

**Comment by rprouse** [comment]
Since this only allows us to work in VS 15, I think we should hold off until we know it works. It may be a Microsoft bug, but it is us who ends up looking bad.

**Comment by CharliePoole** [comment]
@rprouse I agree. This isn't a critical package.

**Comment by ChrisMaddock** [comment]
@OsirisTerje - I added a commit for https://github.com/nunit/nunit3-vs-adapter/issues/268 to this branch, to avoid merge conflicts when this is merged. Hope that's ok.

**Comment by rprouse** [comment]
There have been a few updates to VS 2017 RC since we started this issue. We should confirm that the binding redirects have been fixed.

**Comment by OsirisTerje** [comment]
This is now ready for release.    @rprouse , @CharliePoole 
I have also updated the license info, #22 , as per discussion
It has to be a new vsix, so the vsix manifest ID has been changed. 
I have also made release notes and made an installation section under docs.

**Pull request merged**
