### PR TITLE
Change copyright holder from Charlie to Terje

### PR DESCRIPTION
**Pull request by CharliePoole**
This is a very small part of fixes for nunit/governance#12.

I've had no comments on my plan for reassigning copyrights, so I'm starting small with a PR for one project. The @nunit/core-team should review in order to make sure that this is what they want done as a matter of policy. Others will follow.

### CODE REVIEW

**Review by ChrisMaddock — APPROVED** [review]

**Comment by ChrisMaddock** [comment]
I assume the copyrights in the AssemblyInfo.cs files should also be updated?

**Review by jnm2 — CHANGES_REQUESTED** [review]
With the AssemblyInfos Chris mentioned, I think we should either correct or remove the company and copyright attributes.

Is this publisher relevant? I'd expect it to match the assembly company:
https://github.com/nunit/nunit-vs-testgenerator/blob/master/TestGeneration.Extensions.NUnit/source.extension.vsixmanifest#L4

Also, aren't the copyright years also technically changing to 2017? Or how does that work?

**Comment by CharliePoole** [comment]
@ChrisMaddock Will do.

**Comment by CharliePoole** [comment]
s in

As I reread my changes, I realized that testgenerator is categorized as a "contributed project" In my mind, that means that Terje, as the contributor, has more say than everyone else in what goes into the different fields. @OsirisTerje waiting for your comments.

I hate to say it, but maybe we need another policy document, one about copyright. ☹️

**Comment by CharliePoole** [comment]
@ChrisMaddock @jnm2 You both did code-level review here. I'm assuming that you are in agreement with this change in your roles as core team members too!

**Comment by ChrisMaddock** [comment]
My approval was for the concept, yes.

**Comment by jnm2** [comment]
Also: the footer on https://github.com/nunit/docs/wiki/Visual-Studio-Test-Generator
That will have to be changed via Git since the edit link takes you to the main footer.

> I'm assuming that you are in agreement with this change in your roles as core team members too!

I think so, but I feel like I'm missing part of the conversation. Can you clarify how this will change the way I might interact with the test-generator project?

**Comment by CharliePoole** [comment]
No change for how you interact. It establishes who owns the code and licenses it for your use.

It means that Terje is the guy who decides whether to reassign copyright to some other entity. That's pretty fair, I think, since he created it. I wanted to get my name off because I don't feel I have any moral right to make such decisions for code I've never even touched.

Technically, I guess you could say Terje gave me the property rights when he placed my name in the header but (1) I don't accept and (2) it probably takes more than that, legally.

This is all legal stuff. You can find lots of reference on the web to how copyright is what powers open source.

**Comment by jnm2** [comment]
Yup, I'm fine with that.

**Review by rprouse — APPROVED** [review]

**Comment by CharliePoole** [comment]
@OsirisTerje This is waiting for you to review.

**Review by OsirisTerje — APPROVED** [review]
I'm fine with this.

**Pull request merged**
