### PR TITLE
Limit Extension to Visual Studio Enterprise

### LINKED ISSUE #2: Limit Extension to Visual Studio 2015 Enterprise
According to https://msdn.microsoft.com/en-us/library/dn823749.aspx, IntelliTest is only available in Visual Studio Enterprise, so we should prevent the extension from showing up or installing on lower versions.

I tested in Professional and don't get either the Create Unit Test or Create IntelliTest menu items in the context menu.

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #2

I updated the VSIX manifest and incremented the version on all assemblies. I cannot test this though since there are no unit tests and I do not own a copy of Visual Studio Enterprise, only Professional.

@OsirisTerje, do you have a copy of Enterprise that you can test on? If Microsoft wants us to maintain this, they should consider some open source software licenses :wink: 

After you test, we may want to push an update to the gallery to prevent users from installing an extension that does nothing and asking more questions like #1.

### CODE REVIEW

**Comment by CharliePoole** [comment]
I wasn't aware that this requires Enterprise. Frankly, I don't think we, as an Open Source project should be devoting a lot of time to enhancing Visual Studio's most expensive variants.

**Comment by OsirisTerje** [comment]
It should not require Enterprise.  Unit tests work in all Editions. Intellitest mught be Enterprise only for running, but not for creation nor executing the results

**Comment by rprouse** [comment]
Yes, but this is the test creation extension, not the runner which requires Enterprise unless this extension has additional functionality that I am not aware of...

**Comment by rprouse** [comment]
Here is the link to the Microsoft docs for IntelliTest that state it requires Enterprise, https://msdn.microsoft.com/en-us/library/dn823749.aspx

I tried to use it in Professional and don't get any of the mentioned context menu items.

**Comment by OsirisTerje** [comment]
The extensions should not require Enterprise.  It has two parts, Create Unit Test and Create IntelliTest, only the latter require Enterprise, as IntelliTest is a part of Enterprise, but Unit Test creation should work in all editions, including Community.

**Comment by rprouse** [comment]
You are right. I don't know why it wasn't working for me, but I uninstalled the extension and re-installed it and the Create Unit Test menu option is now available. I've recently uninstalled a few problematic extensions, maybe one of them was conflicting?

I will close this PR and update the documentation accordingly.

**Pull request closed without merging**
